package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 05 15:17:58 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StyleImpl() {
    }

    /**
     * Returns the bind variable value for p_buyerId.
     * @return bind variable value for p_buyerId
     */
    public String getp_buyerId() {
        return (String)getNamedWhereClauseParam("p_buyerId");
    }

    /**
     * Sets <code>value</code> for bind variable p_buyerId.
     * @param value value to bind as p_buyerId
     */
    public void setp_buyerId(String value) {
        setNamedWhereClauseParam("p_buyerId", value);
    }


    /**
     * Returns the bind variable value for p_Org_Id.
     * @return bind variable value for p_Org_Id
     */
    public String getp_Org_Id() {
        return (String)getNamedWhereClauseParam("p_Org_Id");
    }

    /**
     * Sets <code>value</code> for bind variable p_Org_Id.
     * @param value value to bind as p_Org_Id
     */
    public void setp_Org_Id(String value) {
        setNamedWhereClauseParam("p_Org_Id", value);
    }
}
