package mnj.mfg.model.server.client;

import mnj.mfg.model.server.common.MainAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 05 18:49:51 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMClient extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMClient() {
    }


    public void FillRollLines() {
        Object _ret = this.riInvokeExportedMethod(this,"FillRollLines",null,null);
        return;
    }

    public void setRollwhereClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClause",null,null);
        return;
    }

    public void popSizeAll(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"popSizeAll",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public void selectAllLines(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void FillRollLines1() {
        Object _ret = this.riInvokeExportedMethod(this,"FillRollLines1",null,null);
        return;
    }

    public void setRollwhereClause1() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClause1",null,null);
        return;
    }

    public void popSizeAll1(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"popSizeAll1",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public void selectAllLines1(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines1",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public String callOperationsHeder(int p_header_id) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callOperationsHeder",new String [] {"int"},new Object[] {new Integer(p_header_id)});
        return (String)_ret;
    }

    public void setSizeWhereClause(String bpo, String stn, String color) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSizeWhereClause",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {bpo, stn, color});
        return;
    }
}
