package mnj.mfg.model.server.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 05 18:49:51 PKT 2016
// ---------------------------------------------------------------------
public interface MainAM extends ApplicationModule {
    void FillRollLines();

    void setRollwhereClause();

    void popSizeAll(Row poprow);

    void selectAllLines(String flag);

    void FillRollLines1();

    void setRollwhereClause1();

    void popSizeAll1(Row poprow);

    void selectAllLines1(String flag);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    String callOperationsHeder(int p_header_id);

    void setSizeWhereClause(String bpo, String stn, String color);
}
